"""Journal watcher adapter package."""

from infrastructure.watcher.discovery import (
    DiscoveryResult,
    InvalidPathOverrideError,
    JournalPathNotFoundError,
    PathDiscoverer,
    PathDiscoveryError,
    PathDiscoveryStrategy,
    SupportedPlatform,
    UnsupportedPlatformError,
    WatcherError,
)
from infrastructure.watcher.engine import (
    FileIngestionEvent,
    FileKind,
    JournalStreamContext,
    JournalTailer,
    ReactorQueueMetrics,
    SnapshotFreshnessTracker,
    SnapshotReader,
    WatcherAuditAction,
    WatcherAuditEvent,
    WatcherHintAction,
    WatcherIngestCommand,
    WatcherIngestReceiver,
    WatcherReactor,
)
from infrastructure.watcher.exceptions import (
    InvalidSnapshotFileTypeError,
    JournalDirectoryAccessError,
    SnapshotCollisionError,
    SnapshotDirectoryAccessError,
    SnapshotIdentificationError,
    SnapshotRegistrationError,
    UnregisteredSnapshotError,
)
from infrastructure.watcher.selector import (
    JournalCandidate,
    JournalSelector,
    StreamPosition,
    parse_journal_timestamp,
)
from infrastructure.watcher.snapshots import (
    CANONICAL_AUXILIARY_SNAPSHOTS,
    CANONICAL_STATUS_FILE,
    SnapshotCandidate,
    SnapshotIdentifier,
    SnapshotRegistry,
)
from infrastructure.watcher.watcher import FileSystemWatcher, JournalWatcher

__all__ = [
    "CANONICAL_AUXILIARY_SNAPSHOTS",
    "CANONICAL_STATUS_FILE",
    "DiscoveryResult",
    "FileIngestionEvent",
    "FileKind",
    "FileSystemWatcher",
    "InvalidPathOverrideError",
    "InvalidSnapshotFileTypeError",
    "JournalCandidate",
    "JournalDirectoryAccessError",
    "JournalPathNotFoundError",
    "JournalSelector",
    "JournalStreamContext",
    "JournalTailer",
    "JournalWatcher",
    "PathDiscoverer",
    "PathDiscoveryError",
    "PathDiscoveryStrategy",
    "ReactorQueueMetrics",
    "SnapshotCandidate",
    "SnapshotCollisionError",
    "SnapshotDirectoryAccessError",
    "SnapshotFreshnessTracker",
    "SnapshotIdentificationError",
    "SnapshotIdentifier",
    "SnapshotReader",
    "SnapshotRegistrationError",
    "SnapshotRegistry",
    "StreamPosition",
    "SupportedPlatform",
    "UnregisteredSnapshotError",
    "UnsupportedPlatformError",
    "WatcherAuditAction",
    "WatcherAuditEvent",
    "WatcherError",
    "WatcherHintAction",
    "WatcherIngestCommand",
    "WatcherIngestReceiver",
    "WatcherReactor",
    "parse_journal_timestamp",
]
